### ISSUE TITLE
"Malformed UTF-8 at line 4 col 5624"

### ISSUE THREAD

**Issue by cschwenz** [perl6/perl6-lwp-simple#13]
```
===> Testing: LWP::Simple:ver('0.090'):auth('Cosimo Streppone')
Malformed UTF-8 at line 4 col 5624
  in block  at /Users/cal/.zef/store/perl6-lwp-simple.git/243de4fdcc38e1d3049d39aeea7320e19cc8125b/lib/LWP/Simple.pm (LWP::Simple) line 126
  in method request_shell at /Users/cal/.zef/store/perl6-lwp-simple.git/243de4fdcc38e1d3049d39aeea7320e19cc8125b/lib/LWP/Simple.pm (LWP::Simple) line 106
  in method get at /Users/cal/.zef/store/perl6-lwp-simple.git/243de4fdcc38e1d3049d39aeea7320e19cc8125b/lib/LWP/Simple.pm (LWP::Simple) line 31
  in method getstore at /Users/cal/.zef/store/perl6-lwp-simple.git/243de4fdcc38e1d3049d39aeea7320e19cc8125b/lib/LWP/Simple.pm (LWP::Simple) line 346
  in block <unit> at t/getstore.t line 17
```

the `perl6 --version` is:
```
This is Rakudo version 2017.06-119-g04746490c built on MoarVM version 2017.06-29-ga51ba620
implementing Perl 6.c.
```

**Comment by PWBENNETT** [comment]
This is solved by running `zef install Encode` before installing LWP::Simple. My guess is that Encode ought to be declared as a prereq.

**Comment by zoffixznet** [comment]
> Encode ought to be declared 

More likely reason is the recent introduction of userland encoders to Rakudo. The module worked fine relatively recently and similar issue occurs in other code.

**Comment by AlexDaniel** [comment]
Just stumbled upon this while doing the release prep. So issue happens around here:
https://github.com/perl6/perl6-lwp-simple/blob/bae9ddcae9e2315d4776be38e32488f7a78fda90/lib/LWP/Simple.pm#L126

Believe it or not, `$resp_content` indeed contains malformed utf8.

The problem can be reproduced across all releases, including 2015.12 and the upcoming 2017.12: https://gist.github.com/Whateverable/08e7db4ae94e87b041b3c035f8e595d0
You have to run it several times though to make it appear, and surprisingly this is the first time I saw several modules being unsucced in the toaster because of that issue. Intermittent as hell.

**Comment by PWBENNETT** [comment]
Do bugs regularly just spontaneously disappear? If it's definitely gone, can you point out the PR that made it go away?

**Comment by JJ** [comment]
@PWBENNETT well, if it's a problem external to the module they might. I'll see anyway if I can find where that happened...
